name: face_recognition
description: Project to test facial recognition with the camera.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  camera: ^0.10.5
  path: ^1.8.3
  path_provider: ^2.0.15
  google_mlkit_face_detection: ^0.6.0
  lottie: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/